<?php 

/**
 * home class
 */

// parent::view($name); // TODO: Change the autogenerated stub
// echo "This is a Home Controller";


// $arr['ROA_ABBR'] = "IM"; // to insert, first and where functions

// $result = $this->delete(20, "roa_id"); to delete (value, column name)

// $arr['roa_name'] = "potang ina"; // to update (value, column name)
// $result = $this->update(30, $arr, "roa_id"); // for upadte (primary key value, specified column for where)

// $result = $this->query();
// show($result);

class Home
{
	use Controller, Database;

	public function index()
	{

        $User = new User;

//        $result = $this->selectall();
//        show($result);     RIGHT HERE!!!!!!!!!!!!!!!!!

        $this->view('home/home');
	}

}



